### ISSUE TITLE
Production and  development set-ups

### ISSUE THREAD

**Issue by constantinpape** [mobie-org/mobie#6]
We should have production and development set-ups for the MoBIE components.
I.e. a stable production set-up that users can rely on and a dev set-up we can use to test new features.

This is especially relevant for the fiji viewer. For this, @tischi started a discussion already:
https://forum.image.sc/t/imagej-update-site-versions/38427
Currently, the best solution seems to be to have two fiji update sites for this.

It's also important for the dataset repositories. There, we can simply handle it by having development / feature branches. 
@tischi this means the fiji viewer needs to support reading from different branches than `master`.
I am not sure if this is currently possible. This option should probably exposed only in the `Experts ...` mode though.

cc @martinschorb

**Comment by tischi** [comment]
> Currently, the best solution seems to be to have two fiji update sites for this.

I already have now an update site `EMBL-CBA-beta`. I will try to populate it today such that you can test it. I already can forsee that the `EMBL-CBA-beta` will not be compatible with the `EMBL-CBA`. That means everybody would need to have two versions of Fiji on their computer to test both, but I guess this is acceptable and makes sense anyway because you always want to have one "stable" Fiji anyway.

> @tischi this means the fiji viewer needs to support reading from different branches than master.
I am not sure if this is currently possible

I already changed the core to support this. Adding the UI is easy.
But before I actually do it I would like to await the outcome of this discussion: https://github.com/mobie-org/mobie/issues/8

**Comment by constantinpape** [comment]
> That means everybody would need to have two versions of Fiji on their computer to test both, but I guess this is acceptable and makes sense anyway because you always want to have one "stable" Fiji anyway.

Yes, that's fine.

> But before I actually do it I would like to await the outcome of this discussion: #8

I am a bit lost in the discussion there, but I will try to comment ...

**Comment by tischi** [comment]
> I am a bit lost in the discussion there,

Me, too ;-)
That's why I thought we need the discussion.

**Comment by constantinpape** [comment]
We have MoBIE and MoBIE-beta for this now.
